### ISSUE TITLE
How to set hotkey with modifier e.g. shift+f3?

### ISSUE THREAD

**Issue by zizhengwu** [tfurci/MuteActiveWindow#14]
Thanks for the script. It's working and very nice!

I'm wondering how to set hotkey to e.g. shift+f3

I tried putting

```
+F3
```

in `hotkey.txt`. However, it doesn't seem to work (?) Did I configure anything wrong?

**Comment by tfurci** [comment]
Thank you for finding the issue, is should be fixed with the release of v7.5.0, let me know if it works for you.
Release should be available soon or you can use built in updater.

**Comment by zizhengwu** [comment]
Yes, it's working now! That's great. Thanks a lot for the quick fix!
