### ISSUE TITLE
Do I have to be careful using this when playing?

### ISSUE THREAD

**Issue by Pableske** [tfurci/MuteActiveWindow#18]
Hello. I would like to use it in valorant to mute the game when I die, Do I get into the game files or something like that?

**Comment by tfurci** [comment]
The script is designed to operate independently of the game, without any direct interaction or read/write access to game's memory so it should be safe and i haven't had any problems with other games and their anti-cheat systems.
Tho i haven't tested it yet with Valorant but i will download it and play for few days just to be sure.
